"""fix_agents_created_at_default

Revision ID: aaca07b20ea9
Revises: f79da474c69d
Create Date: 2026-02-01 01:11:12.645015

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaca07b20ea9"
down_revision: Union[str, None] = "f79da474c69d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index on agents.id if it doesn't exist
    try:
        op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    except Exception:
        pass  # Index might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index on agents.id
    try:
        op.drop_index(op.f("ix_agents_id"), table_name="agents")
    except Exception:
        pass  # Index might not exist
    # ### end Alembic commands ###
