"""add_token_usage_tracking_to_tasks

Revision ID: 20250128_add_token_tracking
Revises: c4376bc9cd25
Create Date: 2025-01-28 22:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20250128_add_token_tracking"
down_revision: Union[str, None] = "c4376bc9cd25"  # Fix: depend on latest head
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add token usage tracking columns to tasks table.

    This migration adds columns for tracking token usage during task execution:
    - input_tokens: Number of tokens in prompts sent to LLM
    - output_tokens: Number of tokens generated by LLM
    - total_tokens: Total tokens used (input + output)
    - llm_calls: Number of LLM API calls made
    - token_usage_details: Detailed breakdown by model/call type (JSON)

    Compatible with both SQLite and PostgreSQL.
    """
    # Add input_tokens column
    op.add_column(
        "tasks",
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    # Add output_tokens column
    op.add_column(
        "tasks",
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    # Add total_tokens column
    op.add_column(
        "tasks",
        sa.Column("total_tokens", sa.Integer(), nullable=False, server_default="0"),
    )

    # Add llm_calls column
    op.add_column(
        "tasks",
        sa.Column("llm_calls", sa.Integer(), nullable=False, server_default="0"),
    )

    # Add token_usage_details column (JSON)
    # For SQLite, JSON is stored as TEXT with JSON validation
    # For PostgreSQL, it's stored as JSONB with efficient querying
    op.add_column("tasks", sa.Column("token_usage_details", sa.JSON(), nullable=True))


def downgrade() -> None:
    """Remove token usage tracking columns from tasks table."""

    # Remove columns in reverse order
    op.drop_column("tasks", "token_usage_details")
    op.drop_column("tasks", "llm_calls")
    op.drop_column("tasks", "total_tokens")
    op.drop_column("tasks", "output_tokens")
    op.drop_column("tasks", "input_tokens")
