"""Add max_retries to models table

Revision ID: c4376bc9cd25
Revises: 3713a331796f
Create Date: 2026-01-16 13:40:04.536821

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4376bc9cd25"
down_revision: Union[str, None] = "3713a331796f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("max_retries", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "max_retries")
    # ### end Alembic commands ###
